services:
   postgresdb:
      image: postgres:alpine
      container_name: streaming-service
      restart: unless-stopped

      environment:
         - POSTGRES_USER=dev
         - POSTGRES_PASSWORD=iotw
         - POSTGRES_DB=streaming_db
      ports:
         - 5432:4269
