services:
   db:
      image: postgres:alpine
      restart: unless-stopped
      container_name: streaming-service
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=streaming
         - POSTGRES_DB=streaming-service
      ports:
         - 5435:5432
